# NumPy

In [1]:
import numpy as np

## NumPyの配列の生成

In [2]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [3]:
type(x)

numpy.ndarray

## NumPyの算術計算

element-wiseな計算。

In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [5]:
x - y

array([-1., -2., -3.])

In [6]:
x * y

array([ 2.,  8., 18.])

In [7]:
x / y

array([0.5, 0.5, 0.5])

要素の数が異なるとエラーになるらしい。

スカラ値との計算はブロードキャストという機能で実現されている。

In [8]:
x / 2.0

array([0.5, 1. , 1.5])

## NumPyのN次元配列

In [9]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


`shape`で形状を、`dtype`で要素のデータ型を参照できる。

In [11]:
A.shape

(2, 2)

In [12]:
A.dtype

dtype('int32')

行列のelement-wiseな算術計算も配列の場合と同様に行える。

In [13]:
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [14]:
A * B

array([[ 3,  0],
       [ 0, 24]])

ブロードキャストによってスカラとの計算もできる。

In [15]:
A * 10

array([[10, 20],
       [30, 40]])

## ブロードキャスト

形状の異なる配列は良い感じに拡張してくれる。

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

In [17]:
C = np.array([[10, 20]])
A * C

array([[10, 40],
       [30, 80]])

In [19]:
D = np.array([[1, 2], [3, 4], [5, 6]])
# A * D

# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# <ipython-input-18-8bc409950d03> in <module>()
#       1 D = np.array([[1, 2], [3, 4], [5, 6]])
# ----> 2 A * D
#
# ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [20]:
B.shape

(2,)

In [21]:
C.shape

(1, 2)

## 要素へのアクセス

通常の配列と同じようにインデックスでアクセスできる。

In [22]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [23]:
X[0]

array([51, 55])

In [24]:
X[0][1]

55

In [25]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


配列でインデックスを指定して要素を取得できる。

In [26]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [27]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

Booleanの配列で要素を取り出すこともできる。

In [28]:
X > 15

array([ True,  True, False,  True, False, False])

In [29]:
X[X>15]

array([51, 55, 19])