# 3章

## 多次元配列の計算

### 多次元配列

In [1]:
import numpy as np

1次元の配列

In [2]:
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [3]:
np.ndim(A)

1

In [4]:
A.shape

(4,)

In [5]:
A.shape[0]

4

2次元の配列

In [6]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
np.ndim(B)

2

In [8]:
B.shape

(3, 2)

### 行列の積

2x2と2x2の積

In [11]:
A = np.array([[1, 2], [3, 4]])
A.shape

(2, 2)

In [12]:
B = np.array([[5, 6], [7, 8]])
B.shape

(2, 2)

In [13]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

2x3と3x2の積

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [15]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B.shape

(3, 2)

In [16]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

型が合わないとエラーになる

In [17]:
C = np.array([[1, 2], [3, 4]])
C.shape

(2, 2)

In [18]:
A.shape

(2, 3)

In [20]:
# np.dot(A, C)

# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# <ipython-input-19-bb5afb89b162> in <module>()
# ----> 1 np.dot(A, C)
#
# ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

3x2の行列と2次のベクトルの積

In [21]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A.shape

(3, 2)

In [23]:
B = np.array([7, 8])
B.shape

(2,)

In [24]:
np.dot(A, B)

array([23, 53, 83])

### ニューラルネットワークの行列の積

In [25]:
X = np.array([1, 2])
X.shape

(2,)

In [26]:
W = np.array([[1, 3, 5], [2, 4, 6]])
W.shape

(2, 3)

In [27]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
