# 3章

## 出力層の設計

### ソフトマックス関数

In [1]:
import numpy as np

In [2]:
a = np.array([0.3, 2.9, 4.0])

In [3]:
exp_a = np.exp(a)
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [5]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [6]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [7]:
print(np.sum(y))

1.0


In [8]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

### ソフトマックス関数の実装上の注意

大きな数字が入るとオーバーフローしてしまう。

In [9]:
print(softmax(np.array([1010, 1000, 990])))

[nan nan nan]


C:\Users\itsuki\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


logの性質を利用してオーバーフローの対策をする。

In [10]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

### ソフトマックス関数の特徴

In [11]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [12]:
np.sum(y)

1.0