# 4章

## 勾配

### ニューラルネットに対する勾配

In [1]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [2]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [3]:
net = simpleNet()
print(net.W)

[[ 1.66609378  1.3359403   0.63028227]
 [-0.39141516  0.26157199  1.1718171 ]]


In [4]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[0.64738263 1.03697897 1.43280476]


In [5]:
np.argmax(p)

2

In [6]:
t = np.array([0, 0, 1])
net.loss(x, t)

0.7556761989709452

In [9]:
f = lambda w: net.loss(x, t)

In [10]:
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.12848741  0.18969684 -0.31818425]
 [ 0.19273111  0.28454527 -0.47727638]]
